### ISSUE TITLE
Icons in buttons without text are not correctly aligned in the center

### ISSUE THREAD

**Issue by gituon** [mindsmash/mindsmash-ui#31]
Example: `<button class="btn btn-xs"><i class="zmdi zmdi-delete"></i></button>`

**Comment by fynnfeldpausch** [comment]
This is addressed by the `.btn-zmdi` class. Use it as described in the docs: `<button class="btn btn-xs btn-zmdi"><i class="zmdi zmdi-hc-fw zmdi-delete"></i></button>`
